### ISSUE TITLE
"Unsupported wstrust endpoint version" error after login -u on CLI.

### ISSUE THREAD

**Issue by amarzavery** [AzureAD/azure-activedirectory-library-for-nodejs#116]
https://github.com/Azure/azure-xplat-cli/issues/2497
Above issue on xplat cli has more info.

**Comment by toddfoust** [comment]
Are you still facing this issue? It looks like this might have been corrected with the [#70 fix](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/commit/5eb13cd5b347d66166048586336661f6b72c8071) 
If you are still facing this issue, can you elaborate on the failing scenario conditions? 

1. Which version of Azure CLI are you running? azure -v
2. Can you identify if the user you are logging in as has Multi-factor Auth enabled on their account or not
3. If you can repro the problem then can you turn on ADAL logging output, then repeat the failed login with verbose tracing?

       set AZURE_ADAL_LOGGING_ENABLED=1
       azure login -vv -u {user_email}

4. Share the output for review, removing any PII as needed.

**Comment by jmckennon** [comment]
Closing this as it's been some time since a response and we'll be assuming this is no longer a problem.

All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
