### ISSUE TITLE
AADSTS9002313: Invalid request. Request is malformed or invalid.

### ISSUE THREAD

**Issue by mkopacz** [AzureAD/azure-activedirectory-library-for-nodejs#219]
Hi, I keep getting the following error from the `acquireTokenWithAuthorizationCode` method:

```
Error: Get Token request returned http error: 400 and server response:
{
  "error": "invalid_grant",
  "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: <REMOVED>\r\nCorrelation ID: 5b7c06c8-f9d2-46be-9fd0-c1aa18c278a9\r\nTimestamp: 2019-05-23 13:15:22Z",
  "error_codes": [
    9002313
  ],
  "timestamp": "2019-05-23 13:15:22Z",
  "trace_id": "<REMOVED>",
  "correlation_id": "5b7c06c8-f9d2-46be-9fd0-c1aa18c278a9"
}
```

It used to work for about 1 year and all of a sudden started returning errors last week. I suspect it might be caused by some configuration changes in Azure AD, but I don't have access to it and can't check anything there.

Are you able to check what is wrong based on the correlation ID?
Any help appreciated :)

**Comment by sameerag** [comment]
@mkopacz 
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new. repo.
