### ISSUE TITLE
Regression in v0.2.1 - api-version=1.0 is appended to the url

### ISSUE THREAD

**Issue by haonliu** [AzureAD/azure-activedirectory-library-for-nodejs#226]
Hi, 

I'm using adal-node@0.2.1, but I don't see change #186 in this version. After switch back to v0.2.0, the change is there but the typings are not matching, for example, AuthenticationContext's constructor expects 3 params instead of 4.

**Comment by haonliu** [comment]
related: #94 #105

**Comment by devaradhanm** [comment]
Is there any update on this issue?

**Comment by jeffwilcox** [comment]
I'm wondering the same... the 'Releases' page on GitHub and the changelog.md do not include anything about the v0.2.1 version.

**Comment by sameerag** [comment]
@jeffwilcox

Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issue against the new repo.

Please reach out to me offline too, and we can help migrate your team as needed.

**Comment by jeffwilcox** [comment]
@sameerag thanks, we were able to migrate, thanks.
