### ISSUE TITLE
SharePoint Online question

### ISSUE THREAD

**Issue by quantrpeter** [AzureAD/azure-activedirectory-library-for-nodejs#230]
Hi, possible to use this library to get the accessToken of SharePoint online by passing username+password? thanks

**Comment by nilesh-verma** [comment]
Hii ,Have you got any solution to get access token in sharepoint online without login pop-up.

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new. repo.

Your scenario should work with msal-node, though ideally we want to limit users for ever using username-password flow for the inherent security risks with that particular flow.
