### ISSUE TITLE
xmldom dependency issue

### ISSUE THREAD

**Issue by angular-git-user** [AzureAD/azure-activedirectory-library-for-nodejs#231]
Hello, 
We have an application which has a dependency on 
@azure/service-bus.
The dependency hierearchy goes like this

```
{
  "dependencies": {
    "myapp": {
      "dependencies": {
        "@azure/service-bus": {
          "dependencies": {
            "@azure/ms-rest-nodeauth": {
              "dependencies": {
                "adal-node": {
                  "dependencies": {
                    "xmldom": {
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

My application works on NodeJS 8. But I see that adal-node has dependency on
`"xmldom@>= 0.1.x"` . I expected this to pull latest version of xmldom 0.1.x but I see that it in facts pull `xmldom@0.3.0`.

There was a recent update in xmldom 0.3.0 which has dependecy on NodeJS 10. 

Can you make changes to this dependency to be just `xmldom : 0.1.x` ?

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new. repo.
