### ISSUE TITLE
Deno integration with AD

### ISSUE THREAD

**Issue by aadamsx** [AzureAD/azure-activedirectory-library-for-nodejs#236]
Now that Deno has hit version 1.0, can we get AD integration like we have for Node?

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. 

Deno support is not yet available in msal-node but tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2273)
