### ISSUE TITLE
Token not working for NodeJS

### ISSUE THREAD

**Issue by AlexisVirgen** [AzureAD/azure-activedirectory-library-for-nodejs#237]
Hi Im trying to get access to an API using a bearer token, using the adal function `acquireTokenWithClientCredentials`. I received token successfully, but when I try to use it for the API it doesnt work. 

Its weird because if I retrieve the token using the same adal function (using the same credentials and API) but with Python, the token works. I dont know if there is a problem with my AAD or something, but I've done this with the Python adal module with no problem, using exactly the same apparently for the adal nodejs version doesnt work. I can generate two tokens using the same credentials and same function, one with Python and the other with NodeJS, and only the Python one works.

**Comment by AlexisVirgen** [comment]
The problem was in the token response, the resource is returned with `spn:{id}`. The solution is address here: AzureAD/azure-activedirectory-library-for-python/issues/54

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new. repo.
