### ISSUE TITLE
Cache is shared across instances of `AuthenticationContext`

### ISSUE THREAD

**Issue by Stono** [AzureAD/azure-activedirectory-library-for-nodejs#249]
Please see my issue on https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/391 for more information including how to replicate.

At a summary level, it appears when you instantiate `new AuthenticationContext`, the `MemoryCache` is shared with all other `AuthenticationContext` instances, this is pretty bad / security issue in my opinion as you create a new authenticationContext but can get token responses back from other instances.

Explicitly creating a new memory cache on the implementation "fixes" it:

```
    const cache = new MemoryCache()
    const context = new AuthenticationContext(
      `https://${authorityHost}/${tenantId}`,
      true,
      cache
    )
```

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still facing an issue,  please feel free to open an issues against the new repo.
