### ISSUE TITLE
Make "azure login" error message friendlier

### ISSUE THREAD

**Issue by amarzavery** [AzureAD/azure-activedirectory-library-for-nodejs#43]
Please refer this issue filed in xplat cli repo: https://github.com/Azure/azure-xplat-cli/issues/1612 

Fix the typo error: 

```
TokenRequest.prototype.getTokenWithUsernamePassword = function(username, password, callback) {
  this._log.info('Acquiring token with username password');

  this._userId = username;
  this._getToken(callback, function(innerCallback) {
    var self = this;
    this._userRealm = this._createUserRealmRequest(username);
    this._userRealm.discover(function(err) {
      if (err) {
        innerCallback(err);
        return;
      }

      switch(self._userRealm.accountType) {
        case AccountType.Managed:
          self._getTokenUsernamePasswordManaged(username, password, innerCallback);
          return;
        case AccountType.Federated:
          self._getTokenUsernamePasswordFederated(username, password, innerCallback);
          return;
        default:
          innerCallback(self._log.createError('Server returned an unknown AccountType: ' + self._userRealm.AccountType));
      }
    });
  });
```

self._userRealm.AccountType should be self._userRealm.**a**ccountType

**Comment by amarzavery** [comment]
@RandalliLama -  Can you please look at this issue?

**Comment by RandalliLama** [comment]
Investigating.  I would never have expected to actually hit that case.

**Comment by amarzavery** [comment]
@RandalliLama - Thank you

**Comment by RandalliLama** [comment]
@amarzavery  I'll get a fixed up error message out by the end of the week.  It will read something like "Username and password authentication is not supported for this account.  This usually means that the account is a guest account, either from another tenant or a Microsoft Account."

**Comment by squillace** [comment]
I have a problem with this. How can a "Microsoft account" be a "guest account"? This does not help any user understand what they are supposed to do....

**Comment by ahmetalpbalkan** [comment]
@RandalliLama I wonder if we can make this message any more complicated for the end user. The reason this issue is opened because of Azure/azure-xplat-cli#1612.

From AAD end the error might make perfect sense but I am a person using only Azure Storage over Xplat cli and I don't care about AAD terminology like `guest account` `tenant` `Microsoft account`. Please do not give me sentences like that.

I think we should return a specific error code/bool that xplat cli can take and interpret itself.

**Comment by RandalliLama** [comment]
@ahmetalpbalkan I think that there are two separate issues in your comment.

I completely agree with your complexity complaint.  This is simply too complicated.  Unfortunately, that isn't going to change in the next month or so.  That means that when the user hits this issue we have to figure out a way to tell them what they can do about it, or at least what is blocking them.  I agree with your comment that the terms involved are impenetrable to end users.  I appreciate the push back on that.  The problem of explaining a complex failure to an end user exists regardless of which component is responsible for informing the user that they can't make progress.  I haven't come up with a better error message than my suggestion above.  However, given the push back I will give it more thought, and discuss with some other people around the office, before rev'ing the library.  I am open to suggestions as well.

The second issue you raise is that the caller should have a programatic way of determining what went wrong so that they can take appropriate action on behalf of the user if appropriate.  Makes sense.  When I wrote the library I didn't see a lot of people using error codes in Node.  Perhaps my research was not comprehensive enough.  I have opened issue #44 to track this issue.

In the short term I will work on an error message to see if we can put a band-aid on the situation.  I'll work on #44 in the somewhat longer term.

**Comment by ahmetalpbalkan** [comment]
@RandalliLama thanks! That sounds great. It appears like we can give more helpful error messages with some links (e.g. https://github.com/Azure/azure-xplat-cli/issues/1614#issuecomment-79415873) in the xplat-cli. 

Error code was just an idea to give the caller a way to determine type of the error, I have no idea about node.js so things might be different over there. Thanks again.

**Comment by ahmetalpbalkan** [comment]
I'm still seeing a very unfriendly error message (HTTP 500 XML response spitted out to my console) in `azure login` command with bad credentials. Any plans to fix this?

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) There is plans to add a similar node.js wrapper to `msal js`, as can be seen on our roadmap [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap). `adal js`, and the adal-node wrapper, is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
