### ISSUE TITLE
Support for Resource Owner Password Grant

### ISSUE THREAD

**Issue by DonMartin76** [AzureAD/azure-activedirectory-library-for-nodejs#98]
Hello,

I suppose it's on purpose you have not implemented the Resource Owner Password grant for Azure AD? In principle, it's almost there, you just would have to add a `clientSecret` to the TokenRequest, extend `createOAuthParameters` with `CLIENT_SECRET` and add an extra parameter `clientSecret` to the `acquireTokenWithUsernamePassword` method of `AuthenticationContext` (tried it, it works).

Before I would create a PR for that, I thought I'd ask whether it's actually desired or not.

Best regards,
Martin

**Comment by phedinkus** [comment]
+1

**Comment by weijjia** [comment]
Per spec for resource owner password grant, we're supporting it with the username/password flow.

**Comment by phedinkus** [comment]
@weijjia @RandalliLama We are authenticating in order to use the Microsoft Graph API. When we don't include the client secret we get an error saying it is required. We are successfully authenticating by calling our modified `acquireTokenWithUsernamePassword` with resource ("https://graph.microsoft.com"), username, password, clientID, clientSecret and a callback. 

Is there something else we can do to get this integrated?

**Comment by RandalliLama** [comment]
@phedinkus Sorry I didn't catch on earlier but, if I understand correctly you are trying to write a web app or api that uses a users username and password to authenticate to graph.  If so, we explicitly do not support that.  The point of OAuth is that your web app doesn't ever need to be exposed to the users credentials.  You should be using this sample:

https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/sample/website-sample.js

Or maybe I do not understand your scenario well enough.

**Comment by neall** [comment]
@RandalliLama Sorry for taking so long to get back to you - I missed this comment when it came through.

@phedinkus and I aren't writing a web app directly - we're writing a library. And while I'm sure that most of the apps written in Node have a web front end, there is a large class of utility apps that won't - especially in a line-of-business context.

Do any of the other ADAL libraries omit this flow?

**Comment by hajekj** [comment]
Hello, it appears like Azure AD requires the `clientSecret` to be specified:
```json
{
  "error": "invalid_request",
  "error_description": "AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: ed82693d-d1c5-4e90-a804-2e6051693be9\r\nCorrelation ID: 3b431d0b-3579-4db3-92f2-141783e621f0\r\nTimestamp: 2016-06-24 10:48:51Z",
  "error_codes": [
    90014
  ],
  "timestamp": "2016-06-24 10:48:51Z",
  "trace_id": "ed82693d-d1c5-4e90-a804-2e6051693be9",
  "correlation_id": "3b431d0b-3579-4db3-92f2-141783e621f0"
}
```
It happens when I try to run the sample only https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/master/sample/username-password-sample.js (with correct credentials filled out). I believe that if you compare this to the ADAL for .NET, you will see that the request to AAD with resource owner credentials contains the clientSecret.

Can you please look into this more?

**Comment by ivishwas-s** [comment]
@neall @phedinkus Were you able to get a fix for this by any chance?

**Comment by kgroat** [comment]
This is still broken, despite the fact that there is an open PR (#99) to fix it.

Is there any plan to merge said PR?

**Comment by RandalliLama** [comment]
@kpanwar @aashiman

**Comment by pursual** [comment]
This should be merged!

**Comment by kpanwar** [comment]
We got similar PR in java and .net and we have decided to not support this flow in any library.
